# Generated by Django 5.1.2 on 2024-10-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=12, unique=True)),
                ('location', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', '1'), ('female', 'f'), ('other', 'o')], max_length=50)),
                ('isactive', models.BooleanField(default=True)),
                ('account_created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
