# Generated by Django 5.1.2 on 2024-10-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='isactive',
            new_name='active',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'm'), ('female', 'f'), ('other', 'o')], max_length=50),
        ),
    ]
