# Generated by Django 5.1.2 on 2024-10-18 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0002_rename_isactive_user_active_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='conformpassword',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=50),
        ),
    ]
