# Generated by Django 5.1.2 on 2024-10-18 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0004_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discriptiion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='conformpassword',
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
