# Generated by Django 5.1.2 on 2024-10-18 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginsignup', '0007_remove_user_active_user_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discriptiion',
            new_name='description',
        ),
    ]
